version: '3.4'

services:
    ubuntu:
        build: .
        image: ubuntu:nvm
        container_name: ubuntu-node
        user: dev
        volumes:
            - ../package.json:/home/dev/code/package.json
            - ../package-lock.json:/home/dev/code/package-lock.json
            - ../.nvmrc:/home/dev/code/.nvmrc
            - ../school:/home/dev/code/school
            - ./run.sh:/home/dev/code/run.sh
        working_dir: /home/dev/code
