version: '3.4'

services:
    ubuntu:
        build: .
        image: ubuntu:nvm
        container_name: ubuntu-node
        volumes:
            - ../package.json:/root/code/package.json
            - ../package-lock.json:/root/code/package-lock.json
            - ../.nvmrc:/root/code/.nvmrc
            - ../school:/root/code/school
            - ../challenges:/root/code/challenges
            - ./run.sh:/root/code/run.sh
