dist: trusty
language: node_js
node_js:
  - "14.17.1"
env:
  - MOZ_HEADLESS=1
before_script:
  - export PATH=$PATH:$TRAVIS_BUILD_DIR/school/support/webdriver/linux
  - chmod +x $TRAVIS_BUILD_DIR/school/support/webdriver/linux/geckodriver
  - ls -l $TRAVIS_BUILD_DIR/school/support/webdriver/linux
script:
  - npm run test
