language: node_js
node_js:
  - "6.9.1"
osx_image: xcode7.3
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - brew install pkg-config cairo pango libpng jpeg giflib
