name: CI

on:
  push:
    branches:
      - master

jobs:
  test:
    name: run tests
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install node
        uses: actions/setup-node@v2
        with:
          node-version-file: ".nvmrc"
      - name: info
        run: |
          node --version
          npm --version
      - name: install
        run: |
          npm install
      - name: tests
        run: |
          npm test
