name: CI

on:
    push:
        branches:
            - master

jobs:
    test:
        name: run tests
        runs-on: ubuntu-latest

        steps:
            - name: checkout code
              uses: actions/checkout@v2
            - name: build
              run: |
                  cd support
                  docker compose build ubuntu
            - name: tests
              run: |
                  cd support
                  docker compose run --rm ubuntu ./run.sh
